name: me
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  rive: ^0.13.9
  flutter_native_splash: ^2.4.0
  rive_splash_screen: ^0.1.1
  velocity_x: ^4.2.1
  flutter_animate: ^4.5.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  transparent_image: ^2.0.1
  flutter_svg: ^2.0.10+1


  http: ^1.2.2
  convert: ^3.1.1
  intl: ^0.19.0

  firebase_core: ^3.4.1
  firebase_database: ^11.1.2
  firebase_auth: 5.2.1
  firebase_storage: ^12.3.0
  cloud_functions: ^5.1.1
  firebase_analytics: ^11.3.1
  cloud_firestore: ^5.4.1

  flutter_login: ^5.0.0
  text_form_field_wrapper: ^1.0.0
  image_picker: ^1.1.2
  font_awesome_icon_class: ^0.0.6
  google_sign_in: ^6.2.1
  flutter_naver_login: ^1.8.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  google_sign_in_ios:  ^5.7.7
  sign_in_with_apple: ^6.1.2









dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/rive/
  - assets/rive/book_loading.riv
  - assets/image/
  - assets/image/default_user.png
  - assets/icons/
  - assets/icons/bk2.svg
  - assets/icons/heart.svg
  - assets/image/books/
  - assets/image/books/미스터프레지던트.jpeg
  - assets/image/books/이기적유전자.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
