// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWigi-FkR-PCGDdrKXU3NTOapJA9RWmfc',
    appId: '1:311283732407:web:714fa8882a602b5c39a232',
    messagingSenderId: '311283732407',
    projectId: 'bookbell-a8579',
    authDomain: 'bookbell-a8579.firebaseapp.com',
    storageBucket: 'bookbell-a8579.appspot.com',
    measurementId: 'G-LCDTJY1701',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-R0zJKrCfnjV5OzzMJ5LDQ2cebfcstWc',
    appId: '1:311283732407:android:03e457c198a3e49b39a232',
    messagingSenderId: '311283732407',
    projectId: 'bookbell-a8579',
    storageBucket: 'bookbell-a8579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvSxetdKjDpLkgsYcikc8baHX-JsP7a2k',
    appId: '1:311283732407:ios:30aff41a058e0fb939a232',
    messagingSenderId: '311283732407',
    projectId: 'bookbell-a8579',
    storageBucket: 'bookbell-a8579.appspot.com',
    iosBundleId: 'com.example.bookbell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvSxetdKjDpLkgsYcikc8baHX-JsP7a2k',
    appId: '1:311283732407:ios:30aff41a058e0fb939a232',
    messagingSenderId: '311283732407',
    projectId: 'bookbell-a8579',
    storageBucket: 'bookbell-a8579.appspot.com',
    iosBundleId: 'com.example.bookbell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWigi-FkR-PCGDdrKXU3NTOapJA9RWmfc',
    appId: '1:311283732407:web:30d9a0626487019739a232',
    messagingSenderId: '311283732407',
    projectId: 'bookbell-a8579',
    authDomain: 'bookbell-a8579.firebaseapp.com',
    storageBucket: 'bookbell-a8579.appspot.com',
    measurementId: 'G-LFB6K8JJB2',
  );
}
